MDFloatLayout:
    MDLabel:
        id: task_label
        halign: 'center'
        markup: True
        text: "[u][size=48][b]My tasks[/b][/size][/u]"
        pos_hint: {'y': .45}
    
    ScrollView:
        pos_hint: {'center_y': .5, 'center_x': .5}
        size_hint: .9, .8

    MDList:
        id: container

    MDFloatingActionButton:
        icon: 'plus-thick'
        on_release: app.show_task_dialog()
        elevation_normal: 12
        pos_hint: {'x': .8, 'y': .05}